#!/usr/bin/env bash
# adsb-pi-setup python web app
# <Description what this module does>
# Written by Dirk Hohndel <dirk@hohndel.org>
# AGPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

# this is no longer a submodule - the user needs to figure out how to get this in place before running the build
if [ ! -f /filesystem/root/usr/local/share/adsb-pi-setup/app.py ]; then
	echo "adsb-pi-setup missing from sources"
        echo "	- please manually check out this project into filesystem/root/usr/local/share/adsb-pi-setup"
	exit 1
fi

unpack /filesystem/root /

  apt-get update --allow-releaseinfo-change
  apt-get install -y python3 python3-pip
  pip install flask

